---
apiVersion: v1
kind: Secret
metadata:
  name: default-liberty-app-3-repo
  namespace: default
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhagarty/default-liberty-app-3-gitops.git
